### PR TITLE
Invalid bankCode shown

### PR DESCRIPTION
**Pull request by sonu-sonam**
BsbNotFound message shown in label

### CODE REVIEW

**Comment by radek1st** [comment]
@Soujanya2107 could you please have a cuke for that?

**Comment by radek1st** [comment]
seems like 
`  × Then user is redirected to payment page`
step is failing too

**Comment by Soujanya2107** [comment]
> @Soujanya2107 could you please have a cuke for that?

Yes sure I think some locator has been changed. Will look into it

**Comment by Soujanya2107** [comment]
> seems like
> ` × Then user is redirected to payment page`
> step is failing too

@radek1st Fixed this and raised PR

**Pull request merged**
